apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these labels are deployment resources
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
# modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}: #assume this will change
  selector:
  # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  # pod template
    template:
      metadata:
        labels:
          app: nginx
          tier: frontend
          purpose: deployment
    spec:   
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion :}} #image version frequently changes
        ports:
        - containerPort: 80   


